name: Go

on:
  push:
    branches: [ tag ]
  pull_request:
    branches: [ tag ]

jobs:

  build_service:
    name: Build service
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get api service dependencies
      working-directory: ./source/api
      run:  |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build api service
      working-directory: ./source/api
      run:  | 
        SET GOARCH=arm
        SET GOOS=linux
        SET GOARM=7
        SET CGO_ENABLED=1
        SET CC=arm-linux-gnueabihf-gcc
        go build -trimpath --ldflags="-w -s" -o "../../xyz.cloud/cloud-api-linux-v1"
      # arm 平台移植: https://blog.51cto.com/13503908/2157169
      # arm-linux-gnueabihf-gcc 安装: https://zhuanlan.zhihu.com/p/25463241

    - name: Deploy to Server
      # 服务地址: https://github.com/AEnterprise/rsync-deploy
      uses: AEnterprise/rsync-deploy@v1.0
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        ARGS: -avz
        SERVER_PORT: ${{ secrets.SSH_PORT }}
        FOLDER: ./xyz.cloud
        SERVER_IP: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USERNAME }}
        SERVER_DESTINATION: /home/app

    - name: Restart Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd /home/app/xyz.cloud
          sh setup.sh